feat: add backend deploy doc
Byzanteam/deploy pull request #1
Opened 2019-09-23 10:50 UTC by jonyhy96

2019-09-23 10:59 UTC, fiveddd approved these changes

2019-09-23 11:51 UTC, fahchen commented on configs/backend/api.local.env
> +# Elasticsearch
这个文件要签进去吗

2019-09-23 11:51 UTC, fahchen commented on docs/backend/deploy.md
> + 2. 将`configs/backend/app`下配置文件重命名
不能直接修改版本管理的文件

2019-09-23 13:05 UTC, fiveddd commented on configs/backend/api.local.env
> +# Elasticsearch
可以吧，不迁进去不好弄

2019-09-23 14:30 UTC, fahchen commented on configs/backend/api.local.env
> +# Elasticsearch
签进去的作为模版，但不要修改

2019-09-23 14:32 UTC, jonyhy96 commented on docs/backend/deploy.md
> + 2. 将`configs/backend/app`下配置文件重命名
部署人员也会提交吗？

2019-09-24 00:23 UTC, fahchen commented on docs/backend/deploy.md
> + 2. 将`configs/backend/app`下配置文件重命名
不会提交

2019-09-24 01:34 UTC, jonyhy96 commented on configs/backend/api.local.env
> +# Elasticsearch
这个文档本身就是给部署人员看的 不会修改

2019-09-24 01:35 UTC, jonyhy96 commented on docs/backend/deploy.md
> + 2. 将`configs/backend/app`下配置文件重命名
这个文档会存在单机部署的时候复用的情况吗

2019-09-24 02:55 UTC, fahchen commented on docs/backend/deploy.md
> +cp configs/backend/api.local.example.env configs/backend/api.local.env
需要用户配置的东西能否放在一个文件，而不是多个文件

2019-09-24 03:44 UTC, jonyhy96 commented on docs/backend/deploy.md
> +cp configs/backend/api.local.example.env configs/backend/api.local.env
这些配置文件分别是 `应用的配置` `docker-compose.yml的环境` `容器运行的环境`，怎么合并到一起？

2019-09-24 06:32 UTC, fahchen requested changes
1. 现在跑起来需要配置的文件较多，且路径太深
2. 跑起来整个步骤还要再简单点

整个思想是尽可能开箱即用，减少使用者的思考

2019-09-24 06:32 UTC, fahchen commented on docs/backend/deploy.md
> +cp configs/backend/api.local.example.env configs/backend/api.local.env
这些命令变成一个命令放到 makefile 里面

2019-09-24 06:32 UTC, fahchen commented on docs/backend/deploy.md
> +export STAGE=DEFAULT # 替换成所使用的STAGE
这种东西写到配置文件里面去，别让使用者手动输入，想办法从配置文件读取

2019-09-24 08:14 UTC, jonyhy96 commented
> 1. 现在跑起来需要配置的文件较多，且路径太深
> 2. 跑起来整个步骤还要再简单点
> 
> 整个思想是尽可能开箱即用，减少使用者的思考

2019-09-24 08:17 UTC, jonyhy96 commented
> 1. 现在跑起来需要配置的文件较多，且路径太深
> 2. 跑起来整个步骤还要再简单点
> 
> 整个思想是尽可能开箱即用，减少使用者的思考

开箱即用这些密钥要直接放在example里吗？

2019-09-24 08:23 UTC, jonyhy96 commented on docs/backend/deploy.md
> +export STAGE=DEFAULT # 替换成所使用的STAGE
[docs: update doc](https://github.com/Byzanteam/deploy/pull/1/commits/0fd6598995d1db9b81f073a6248b0f73e0b1fbb2)

2019-09-24 08:24 UTC, jonyhy96 commented on docs/backend/deploy.md
> +cp configs/backend/api.local.example.env configs/backend/api.local.env
[docs: update doc](https://github.com/Byzanteam/deploy/pull/1/commits/0fd6598995d1db9b81f073a6248b0f73e0b1fbb2)

2019-09-24 10:49 UTC, fahchen commented on Makefile
> +cp-backend-config:
要不判断一下，如果存在就不复制，避免覆盖

2019-09-24 10:50 UTC, fahchen commented
> 路径太深的原因是考虑到之后前端部署文档也会在这个仓库版本管理，用flat的风格会产生很多冲突
> 开箱即用这些密钥要直接放在example里吗？

用 link 呢？

2019-09-24 13:02 UTC, jonyhy96 commented
> > 路径太深的原因是考虑到之后前端部署文档也会在这个仓库版本管理，用flat的风格会产生很多冲突
> > 开箱即用这些密钥要直接放在example里吗？
> 
> 用 link 呢？

什么是link

2019-09-24 15:37 UTC, fahchen commented
链接

2019-09-25 02:55 UTC, jonyhy96 commented on Makefile
> +cp-backend-config:
已修改

2019-09-25 03:16 UTC, fahchen approved these changes

2019-09-25 05:50 UTC, merged